use crate::agent::config::AgentContext;
use crate::agent::context_builder::PromptParts;
use crate::agent::helpers;
use crate::agent::response_handler::handle_response;
use crate::db::types as queries;
use crate::db::types::{Channel, Message, MessageNew, Thread};
use crate::err_msg;
use crate::error::AppResult;
use crate::llm::{ChatMessage, CompletionRequest, LLMClient, Usage};
use crate::mcp::{truncate_content, McpToolCall, McpToolResult, DEFAULT_MAX_TOOL_OUTPUT_CHARS};
use tokio::task::JoinSet;
use tracing::{error, info, warn};

#[allow(clippy::too_many_arguments)]
pub(crate) async fn run_main_loop(
    cfg: &AgentContext,
    thread: &Thread,
    cause_msg: &Message,
    channel: &Channel,
    profile_name: &str,
    tool_names: &[String],
    prompt_parts: PromptParts,
    template_section: Option<String>,
    next_seq: &mut i32,
    per_thread_llm: &LLMClient,
    prof: &crate::profile::Profile,
    start_time: std::time::Instant,
) -> AppResult<Message> {

    // Track cumulative token usage across all LLM calls
    let mut cumulative_usage: Option<crate::llm::Usage> = None;
    let mut force_failed: bool = false;
    let mut current_iter: i32;

    // ── Planning Phase ──
    // Plan is a boolean resolved at thread creation time.
    // When true, the agent runs a planning iteration before the main loop.
    // The planning prompt itself is generated by the prompt plugin
    // the executor just orchestrates the calls.
    let should_plan = thread.plan;

    // Whether subtask tools are enabled for the main loop
    let enable_subtasks = should_plan;

    // Pre-read prompt log level for consistency across planning and main loop
    let prompt_log_level = cfg.config_snapshot().prompt_log_level;
    let prompt_log_level = prompt_log_level.as_str();
    let mut has_logged_first_prompt = false;

    let plan_content: Option<String> = if should_plan {
        let max_iter = 0; // one-shot, no refinement iterations
        let max_tokens = 2048u32; // planning token limit: previously from config
        let mut last_plan: Option<String> = None;
        let mut json_failure_count: u32 = 0;
        let mut json_error_msg: Option<String> = None;

        for iter in 0..(max_iter + 1) {
            // Build planning messages from prompt parts
            // User's request goes in context; planning instruction goes in user
            let mut planning_messages = vec![ChatMessage::system(&prompt_parts.system)];
            if !prompt_parts.memory.is_empty() {
                planning_messages.push(ChatMessage::system(&prompt_parts.memory));
            }
            if !prompt_parts.soul.is_empty() {
                planning_messages.push(ChatMessage::system(&prompt_parts.soul));
            }
            if !prompt_parts.context.is_empty() {
                planning_messages.push(ChatMessage::system(&format!(
                    "=== Context ===\n{}", prompt_parts.context
                )));
            }
            // Inject the task template so the plan is aware of the instructions
            if let Some(ref ts) = template_section {
                planning_messages.push(ChatMessage::system(ts));
            }
            if let Some(ref err) = json_error_msg {
                planning_messages.push(ChatMessage::system(err));
            }
            // Planning instruction as user message
            let tool_list = if tool_names.is_empty() {
                String::new()
            } else {
                format!("Your available tools: {}.", tool_names.join(", "))
            };
            let planning_prompt = if iter == 0 {
                format!(
                    "## Plan\nBefore responding, create a high-level plan with numbered steps. \
{tool_list}\nBe specific about which tool to use and what parameters to pass. \
Aim for the minimum number of steps to complete the task. \
Wrap your plan in a <plan> block. After delivering the final answer, \
evaluate: if the task was completed, call the completion tool."
                )
            } else {
                format!(
                    "## Revised Plan (iteration {}/{})\n\
Your previous plan did not fully complete the task. \
Review what was done vs what remains. Identify the specific \
blockage and create a revised plan. Each step must include \
which tool to use and what parameters.\n\n\
Previous plan:\n{}",
                    iter + 1,
                    max_iter,
                    last_plan.as_deref().unwrap_or("(none)")
                )
            };
            planning_messages.push(ChatMessage::user(&planning_prompt));

            // ── Optional: insert prompt message before planning LLM call ──
            // Logs the prompt *sent to* the LLM (not the returned plan, which is
            // already saved as a separate msg_type="plan" message). Does NOT count
            // as "the first prompt" for main-loop tracking: the main loop's
            // system prompt + context is the important one for debugging.
            // Subtype "plan" indicates this is the first prompt to create a plan.
            if prompt_log_level != "off" {
                let prompt_seq = {
                    let v = *next_seq;
                    *next_seq += 1;
                    v
                };
                let prompt_content =
                    serde_json::to_string(&planning_messages).unwrap_or_else(|_| String::new());
                let prompt_msg = MessageNew {
                    thread_id: thread.id,
                    role: "system".to_string(),
                    content: prompt_content,
                    thread_sequence: prompt_seq,
                    external_id: None,
                    metadata: serde_json::json!({
                        "prompt_log_level": prompt_log_level,
                        "prompt_subtype": "plan",
                        "num_messages": planning_messages.len(),
                    }),
                    embedding: None,
                    summary_text: None,
                    is_summary: false,
                    msg_type: "prompt".to_string(),
                    msg_subtype: Some("plan".to_string()),
                    iteration_number: 0,
                    duration_ms: 0,
                    token_usage: serde_json::json!({}),
                };
                if let Err(e) = queries::create_message(&cfg.pool, &prompt_msg).await {
                    warn!(
                        "[prompt] Failed to persist planning prompt for thread {}: {:?}",
                        thread.id, e
                    );
                }
            }

            let plan_request = CompletionRequest {
                messages: planning_messages,
                max_tokens,
                temperature: 0.3,
                stream: false,
                tools: None,
            };

            match per_thread_llm.completion(plan_request).await {
                Ok(resp) => {
                    helpers::merge_usage(&mut cumulative_usage, resp.usage.clone());
                    let plan_token_usage = resp.usage.as_ref().map(|u| serde_json::json!({
                        "prompt_tokens": u.prompt_tokens,
                        "completion_tokens": u.completion_tokens,
                        "cached_tokens": u.cached_tokens,
                        "reasoning_tokens": u.reasoning_tokens,
                    })).unwrap_or(serde_json::json!({}));
                    let plan_duration_ms = resp.duration_ms as i32;
                    // Use reasoning as fallback when plan content is empty (e.g. DeepSeek
                    // puts everything in reasoning/thinking and leaves content empty).
                    let plan_content = if !resp.content.is_empty() {
                        resp.content.clone()
                    } else if let Some(ref r) = resp.reasoning {
                        if !r.is_empty() {
                            r.clone()
                        } else {
                            String::new()
                        }
                    } else {
                        String::new()
                    };

                    info!(
                        "[plan] Generated plan for thread {} ({} chars from field '{}', iteration {}/{})",
                        thread.id,
                        plan_content.len(),
                        if !resp.content.is_empty() { "content" } else if resp.reasoning.as_ref().is_some_and(|r| !r.is_empty()) { "reasoning" } else { "empty" },
                        iter + 1,
                        max_iter + 1,
                    );

                    // Save the plan as a plan-type message (skip if both content and reasoning are empty)
                    if !plan_content.is_empty() {
                        let plan_msg = MessageNew {
                            thread_id: thread.id,
                            role: "agent".to_string(),
                            content: plan_content.clone(),
                            thread_sequence: {
                                let v = *next_seq;
                                *next_seq += 1;
                                v
                            },
                            external_id: None,
                            metadata: serde_json::json!({
                                "plan_iteration": iter,
                                "plan_accepted": iter == 0 && max_iter == 0,
                            }),
                            embedding: None,
                            summary_text: None,
                            is_summary: false,
                            msg_type: "plan".to_string(),
                        msg_subtype: Some("markdown".to_string()),
                        iteration_number: 1,
                        duration_ms: plan_duration_ms,
                        token_usage: plan_token_usage,
                    };
                                               match queries::create_message(&cfg.pool, &plan_msg).await {
                            Ok(_) => {}
                            Err(e) => warn!(
                                "[plan] Failed to persist plan for thread {}: {:?}",
                                thread.id, e
                            ),
                        }
                    }

                    // Mark first prompt as already logged so the main loop doesn't log
                    // a duplicate "first" prompt that includes the plan content as context.
                    // The planning prompt (msg_subtype="plan") and the plan message itself
                    // already serve as the record: the main-loop "first" prompt would just
                    // embed the plan text again, duplicating what's already saved.
                    has_logged_first_prompt = true;

                    // For complex tasks, auto-create subtasks from JSON plan content
                    if enable_subtasks && plan_content.len() > 100 {
                        let max_json_retries: u32 =
                            cfg.config_snapshot().max_unfinished_subtask_retries;
                        match serde_json::from_str::<serde_json::Value>(&plan_content) {
                            Ok(plan_json) => {
                                if let Some(steps) =
                                    plan_json.get("steps").and_then(|v| v.as_array())
                                {
                                    // Valid JSON with steps: create subtasks
                                    let total = steps.len().min(6);
                                    for (i, step_val) in steps.iter().enumerate().take(6) {
                                        if let Some(step) = step_val.as_str() {
                                            let clean =
                                                step.trim().trim_end_matches(['*', '`']).trim();
                                            if !clean.is_empty() {
                                                let priority = (total - i) as i32;
                                                if let Err(e) = crate::subtask::add_subtask(
                                                    &cfg.pool, thread.id, clean, priority,
                                                )
                                                .await
                                                {
                                                    warn!("[plan] Failed to create subtask '{}': {:?}", clean, e);
                                                } else {
                                                    info!("[plan] Created subtask '{}' for complex thread {}", clean, thread.id);
                                                }
                                            }
                                        }
                                    }
                                } else {
                                    // JSON valid but missing "steps" field
                                    json_failure_count += 1;
                                    if json_failure_count > max_json_retries {
                                        warn!("[plan] JSON validation exhausted: missing 'steps' field after {} retries for thread {}", max_json_retries, thread.id);
                                        force_failed = true;
                                        break;
                                    }
                                    json_error_msg = Some(format!(
                                        "ERROR: Your plan JSON is missing the required \"steps\" array. \
                                         You MUST return a JSON object with \"description\" (string) and \"steps\" (array of strings). \
                                         No surrounding markdown, no backticks, no extra text. \
                                         Attempt {}/{}: fix the JSON or the thread will fail.",
                                        json_failure_count, max_json_retries
                                    ));
                                    last_plan = Some(plan_content.clone());
                                    continue;
                                }
                            }
                            Err(e) => {
                                // Invalid JSON syntax
                                json_failure_count += 1;
                                if json_failure_count > max_json_retries {
                                    warn!("[plan] JSON validation exhausted: invalid JSON after {} retries for thread {}: {}", max_json_retries, thread.id, e);
                                    force_failed = true;
                                    break;
                                }
                                json_error_msg = Some(format!(
                                    "ERROR: Your response was not valid JSON. Parsing error: {}. \
                                     You MUST return a valid JSON object with \"description\" and \"steps\" fields. \
                                     No surrounding markdown, no backticks, no extra text. \
                                     Attempt {}/{}: fix the JSON or the thread will fail.",
                                    e, json_failure_count, max_json_retries
                                ));
                                last_plan = Some(plan_content.clone());
                                continue;
                            }
                        }
                    }

                    last_plan = Some(plan_content);

                    // One-shot: no refinement iterations: plan is final
                    break;
                }
                Err(e) => {
                    warn!(
                        "[plan] Failed to generate plan for thread {}: {:?}",
                        thread.id, e
                    );
                    break;
                }
            }
        }

        last_plan
    } else {
        None
    };

    // 5. Assemble messages from prompt parts
    let mut messages = vec![ChatMessage::system(&prompt_parts.system)];
    if !prompt_parts.memory.is_empty() {
        messages.push(ChatMessage::system(&prompt_parts.memory));
    }
    if !prompt_parts.soul.is_empty() {
        messages.push(ChatMessage::system(&prompt_parts.soul));
    }

    // Inject task template FIRST (right after system prompt): highest instruction priority
    // for template-backed tasks (kanban/cron with template).
    // Flush-left position ensures the template guides the model before any other context.
    if let Some(ref template_section) = template_section {
        messages.push(ChatMessage::system(template_section));
    }

    // Add context from plugin as system message (before the user message)
    if !prompt_parts.context.is_empty() {
        messages.push(ChatMessage::system(&format!(
            "=== Context ===\n{}",
            prompt_parts.context
        )));
    }

    // Inject the plan as execution context if one was generated
    if let Some(ref plan) = plan_content {
        messages.push(ChatMessage::system(&format!(
            "=== Generated Plan (use as guidance) ===\n\
             A plan was generated for the current task. Follow it unless tool results \
             contradict it. Do NOT explore alternative approaches that the plan already \
             considered: adapt only when necessary.\n\n{}",
            plan
        )));
        info!(
            "[plan] Injected plan as context for thread {} ({} chars)",
            thread.id,
            plan.len(),
        );
    }

    // Add the user message (from the prompt parts: the plugin provides this)
    messages.push(ChatMessage::user(&prompt_parts.user));

    // 5. Build tool definitions from the profile's allowed tools
    let tools_def = cfg.plugin_manager.snapshot_registry().await.to_openai_tools(&prof.allowed_tools);

    // 6. Tool-calling loop: max iterations controls total LLM calls
    let iter_limit =
        queries::max_iterations_for_plan(&cfg.config_snapshot(), thread.plan)
            as i32;
    // The plan phase consumed 1 iteration (if it ran). Subtract it so the
    // tool-calling loop gets the remaining budget.
    let plan_consumed = if should_plan { 1 } else { 0 };
    let max_llm_calls = (iter_limit - plan_consumed).max(0) as u32;
    let mut final_content = String::new();
    let mut final_reasoning: Option<String> = None;
    let mut final_tool_call: bool = false;
    let mut limit_reached: bool = false;
    let mut _last_response_usage: Option<Usage> = None;
    current_iter = plan_consumed; // 0 for prompt_only, 1 if plan already ran
    let mut unfinished_subtask_retries: u32 = 0;
    let mut calls_since_subtask_management: u32 = 0;
    // Track when condensation last occurred so soft-budget triggers use
    // iteration-since-last-condense rather than a fixed modulo schedule.
    // This prevents aggressive condensation on every Nth iteration even when
    // the last condense just happened.
    let mut last_condense_iteration: i32 = 0;

    for _turn in 0..max_llm_calls {
        current_iter += 1; // increment before each LLM call

        // If this LLM call will reach the iteration limit, hint to the model
        // to produce a final answer rather than more tool calls.
        if current_iter >= iter_limit {
            messages.push(ChatMessage::system(
                "This is your last turn. You must provide your final answer now. \
                 Do not request additional tool calls.",
            ));
        }

        // ── Context management: call condense tool ──
        // Before each LLM call, invoke the configured condense MCP tool.
        // The tool (plugin-specific) decides whether to condense based on
        // its own thresholds (configurable via plugin config). The agent
        // is agnostic to condensation logic : it passes messages and
        // iteration info and applies whatever the tool returns.
        let cfg_snapshot = cfg.config_snapshot();
        let condense_tool = cfg_snapshot.compact_messages_tool_name.clone();
        if !condense_tool.is_empty() {
            let condense_call = McpToolCall {
                name: condense_tool.clone(),
                arguments: serde_json::json!({
                    "messages": messages,
                    "current_iteration": current_iter,
                    "last_condense_iteration": last_condense_iteration,
                }),
                id: String::new(),
            };
            match cfg.plugin_manager.snapshot_registry().await.execute(&condense_call, cfg.ctx.clone()).await {
                Ok(res) => {
                    if let Ok(result) = serde_json::from_str::<serde_json::Value>(&res.content) {
                        if result.get("was_condensed").and_then(|v| v.as_bool()).unwrap_or(false) {
                            if let Some(condensed) = result.get("messages").and_then(|v| v.as_array()) {
                                messages = serde_json::from_value(serde_json::Value::Array(condensed.clone()))
                                    .unwrap_or(messages);
                                last_condense_iteration = current_iter;
                                let before = result.get("before_count").and_then(|v| v.as_u64()).unwrap_or(0);
                                let after = result.get("after_count").and_then(|v| v.as_u64()).unwrap_or(0);
                                info!(
                                    "[context] Condensed messages via {}: {} → {} (iteration {})",
                                    condense_tool, before, after, current_iter,
                                );
                            }
                        }
                    }
                }
                Err(e) => {
                    warn!("[context] Condense tool '{}' failed: {} : continuing without condensation", condense_tool, e);
                }
            }
        }

        // Layer 3: iteration-aware tool result pruning
        helpers::prune_old_tool_results(&mut messages, current_iter as u32);

        // ── Optional: insert prompt message before LLM call ──
        // Subtypes: "first" (first normal LLM call), "compaction" (after context
        // compaction), "follow_up" (subsequent normal calls).
        let prompt_subtype = if !has_logged_first_prompt {
            "first"
        } else if current_iter == last_condense_iteration {
            "compaction"
        } else {
            "follow_up"
        };
        let should_log_prompt = match prompt_log_level {
            "off" => false,
            "first" => !has_logged_first_prompt,
            "first+compact" => !has_logged_first_prompt || current_iter == last_condense_iteration,
            "all" => true,
            _ => false,
        };
        if should_log_prompt {
            let prompt_seq = {
                let v = *next_seq;
                *next_seq += 1;
                v
            };
            let prompt_content = serde_json::to_string(&messages).unwrap_or_else(|_| String::new());
            let prompt_msg = MessageNew {
                thread_id: thread.id,
                role: "system".to_string(),
                content: prompt_content,
                thread_sequence: prompt_seq,
                external_id: None,
                metadata: serde_json::json!({
                    "prompt_log_level": prompt_log_level,
                    "prompt_subtype": prompt_subtype,
                    "num_messages": messages.len(),
                    "iteration": current_iter,
                    "condensed": current_iter == last_condense_iteration,
                }),
                embedding: None,
                summary_text: None,
                is_summary: false,
                msg_type: "prompt".to_string(),
                msg_subtype: Some(prompt_subtype.to_string()),
                iteration_number: current_iter,
                duration_ms: 0,
                token_usage: serde_json::json!({}),
            };
            if let Err(e) = queries::create_message(&cfg.pool, &prompt_msg).await {
                warn!(
                    "[prompt] Failed to persist prompt for thread {}: {:?}",
                    thread.id, e
                );
            }
            has_logged_first_prompt = true;
        }

        // ── LLM completion call ──

        let request = CompletionRequest {
            messages: messages.clone(),
            max_tokens: cfg.config_snapshot().max_tokens,
            temperature: cfg.config_snapshot().temperature,
            stream: false,
            tools: if tools_def.is_empty() {
                None
            } else {
                Some(tools_def.clone())
            },
        };

        let response = match per_thread_llm.completion(request).await {
            Ok(resp) => resp,
            Err(e) => {
                error!("LLM call failed: {:?}", e);
                final_content = format!("I encountered an error: {}", e);
                break;
            }
        };

        // Track cumulative token usage
        helpers::merge_usage(&mut cumulative_usage, response.usage.clone());

        // Store reasoning if present
        if response.reasoning.is_some() {
            final_reasoning = response.reasoning.clone();
        }

        // Check for tool calls
        if response.tool_calls.is_empty() {
            // Subtask enforcement: only when subtask mode is active
            if enable_subtasks {
                // Check if all subtasks are completed/cancelled before allowing final answer
                let pending_subtasks =
                    match crate::subtask::list_subtasks(&cfg.pool, thread.id).await {
                        Ok(list) => list
                            .into_iter()
                            .filter(|st| st.status == "pending" || st.status == "in_progress")
                            .collect::<Vec<_>>(),
                        Err(_) => Vec::new(),
                    };

                if !pending_subtasks.is_empty()
                    && unfinished_subtask_retries
                        < cfg.config_snapshot().max_unfinished_subtask_retries
                {
                    unfinished_subtask_retries += 1;
                    let max_retries = cfg.config_snapshot().max_unfinished_subtask_retries;
                    let names: Vec<String> = pending_subtasks
                        .iter()
                        .map(|st| format!("#{}: {} ({})", st.id, st.description, st.status))
                        .collect();
                    let feedback = format!(
                        "[Subtask Required] You cannot end this thread while subtasks are still pending. \
                         BEFORE writing your final answer, call `manage_subtasks(action=\"update\", subtask_id=N, status=\"completed\")` \
                         for each subtask you've already finished. If any subtask is no longer needed, use status=\"cancelled\".\n\n\
                         Remaining unfinished subtasks:\n{}\n\n\
                         You will be retried (attempt {}/{}): use this chance to manage them.",
                        names.join("\n"),
                        unfinished_subtask_retries,
                        max_retries,
                    );
                    messages.push(ChatMessage::system(&feedback));
                    info!(
                        "[subtask] Enforcement: LLM tried to end with {} unfinished subtask(s) (retry {}/{})",
                        pending_subtasks.len(),
                        unfinished_subtask_retries,
                        max_retries,
                    );
                    // Don't consume from the iteration budget: this is enforcement overhead
                    current_iter -= 1;
                    continue;
                }

                if !pending_subtasks.is_empty() {
                    let max_retries = cfg.config_snapshot().max_unfinished_subtask_retries;
                    // Exhausted retries: force the thread to fail
                    warn!(
                        "[subtask] Enforcement exhausted after {} retries: {} subtask(s) still unfinished for thread {}",
                        max_retries,
                        pending_subtasks.len(),
                        thread.id,
                    );
                    final_content = format!(
                        "I ran out of attempts to complete all subtasks. The following remain unfinished:\n{}",
                        pending_subtasks.iter().map(|st| format!("- #{}: {} ({})", st.id, st.description, st.status)).collect::<Vec<_>>().join("\n"),
                    );
                    final_tool_call = false;
                    force_failed = true;
                    break;
                }
            }

            // Normal text response: all subtasks done (or subtask mode off)
            final_content = if response.content.is_empty() {
                // When both content and reasoning are empty (e.g. context too large
                // caused the LLM to return nothing), produce a fallback error message
                // and force the thread to fail.
                // Note: DeepSeek with reasoning always returns reasoning=Some(...),
                // even when the reasoning string is empty, so we must check the
                // content of reasoning too, not just whether it's Some/None.
                let reasoning_empty = response
                    .reasoning
                    .as_ref()
                    .map(|r| r.trim().is_empty())
                    .unwrap_or(true); // None means empty too

                // Check if the response has meaningful completion_tokens but empty
                // content: indicates a content filter or provider-side stripping.
                let has_completion = response
                    .usage
                    .as_ref()
                    .map(|u| u.completion_tokens > 0)
                    .unwrap_or(false);

                if reasoning_empty && has_completion {
                    // The API reports generated tokens but returned empty content.
                    // This indicates content was filtered/stripped (provider safety filter).
                    // Log it and produce a clear error rather than hiding it.
                    let prompt_toks = response
                        .usage
                        .as_ref()
                        .map(|u| u.prompt_tokens)
                        .unwrap_or(0);
                    let comp_toks = response
                        .usage
                        .as_ref()
                        .map(|u| u.completion_tokens)
                        .unwrap_or(0);
                    warn!(
                        "[executor] LLM returned empty content with {} completion tokens (prompt: {}): likely content filter",
                        comp_toks, prompt_toks,
                    );
                }

                if reasoning_empty && enable_subtasks {
                    let pending_subtasks =
                        match crate::subtask::list_subtasks(&cfg.pool, thread.id).await {
                            Ok(list) => list
                                .into_iter()
                                .filter(|st| st.status == "pending" || st.status == "in_progress")
                                .collect::<Vec<_>>(),
                            Err(_) => Vec::new(),
                        };
                    force_failed = true; // empty response: thread must fail
                    if pending_subtasks.is_empty() {
                        "The LLM returned an empty response with no pending subtasks: likely caused by context explosion.".to_string()
                    } else {
                        format!(
                            "The LLM returned an empty response. The following subtasks were never completed:\n{}",
                            pending_subtasks.iter().map(|st| format!("- #{}: {} ({})", st.id, st.description, st.status)).collect::<Vec<_>>().join("\n"),
                        )
                    }
                } else if reasoning_empty {
                    // No subtask mode, but content AND reasoning are both empty
                    force_failed = true; // empty response: thread must fail
                    "The LLM returned an empty response: likely caused by context explosion."
                        .to_string()
                } else {
                    // Reasoning has content but no response content. Leave
                    // final_content empty: the reasoning is already saved
                    // as a separate `reasoning` message (step 8 below).
                    // Using reasoning as final_content would cause the
                    // summary message to duplicate the reasoning text.
                    String::new()
                }
            } else {
                response.content
            };
            final_tool_call = false;
            break;
        }

        // If iterations will equal the max after this call, flag interruption
        if current_iter >= iter_limit {
            limit_reached = true;
            // Produce content from the last tool calls so final_content is
            // non-empty: prevents a false "empty response" detection when
            // the iteration budget runs out while the LLM was making tools.
            if !response.tool_calls.is_empty() {
                let tool_names: Vec<String> = response
                    .tool_calls
                    .iter()
                    .map(|tc| tc.function.name.clone())
                    .collect();
                final_content = format!(
                    "Iteration limit reached. Last tool calls issued: {}. The task was interrupted before completion.",
                    tool_names.join(", "),
                );
                final_tool_call = false;
            }
            break;
        }

        // We have tool calls: add assistant message with tool_calls
        final_tool_call = true;
        let mut assistant_msg = ChatMessage::assistant("");
        assistant_msg.tool_calls = Some(response.tool_calls.clone());
        messages.push(assistant_msg);

        // Persist a message showing what tool(s) the agent called
        // (single tool → msg_type: \"tool\", batch → msg_type: \"multi-tool\")
        // Previously only multi-tool was persisted; single tool calls were invisible in the thread.
        let tool_content = response
            .tool_calls
            .iter()
            .map(|tc| {
                format!(
                    "{}: {}",
                    tc.function.name.clone(),
                    tc.function.arguments
                )
            })
            .collect::<Vec<_>>()
            .join("\n");

        let tool_msg_type = if response.tool_calls.len() > 1 {
            "multi-tool"
        } else {
            "tool"
        };

        let tool_call_msg = MessageNew {
            thread_id: thread.id,
            role: "agent".to_string(),
            content: tool_content,
            thread_sequence: {
                let v = *next_seq;
                *next_seq += 1;
                v
            },
            external_id: None,
            metadata: serde_json::json!({}),
            embedding: None,
            summary_text: None,
            is_summary: false,
            msg_type: tool_msg_type.to_string(),
            msg_subtype: None,
            iteration_number: current_iter,
            duration_ms: response.duration_ms as i32,
            token_usage: response.usage.as_ref().map(|u| serde_json::json!({
                "prompt_tokens": u.prompt_tokens,
                "completion_tokens": u.completion_tokens,
                "cached_tokens": u.cached_tokens,
                "reasoning_tokens": u.reasoning_tokens,
            })).unwrap_or(serde_json::json!({})),
        };
        match helpers::persist_or_abort(&cfg.pool, &tool_call_msg, thread.id).await {
            helpers::CreateMessageResult::FkViolation => {
                err_msg!("FK violation: thread {} no longer exists", thread.id);
            }
            helpers::CreateMessageResult::OtherError(e) => {
                error!("Failed to persist tool call message: {:?}", e)
            }
            helpers::CreateMessageResult::Success(saved) => {
                helpers::enqueue_delivery(
                    &cfg.ctx,
                    &saved,
                    &channel,
                    thread,
                    cause_msg.external_id.clone(),
                )
                .await;
            }
        }

        // ── Parallel tool execution ──
        // Execute all tool calls concurrently, each inserts its own consolidated
        // result message (JSON: {tool, input, output}) as it finishes.
        // LLM-facing ChatMessages are collected and pushed in original call order
        // after all tools complete.
        let tool_count = response.tool_calls.len();

        // Pre-allocate sequence numbers for each result message
        let result_seqs: Vec<i32> = (0..tool_count)
            .map(|_| {
                let v = *next_seq;
                *next_seq += 1;
                v
            })
            .collect();

        let pool = cfg.pool.clone();
        // mcp_registry removed - use cfg.plugin_manager instead
        let mut join_set = JoinSet::new();

        for (idx, tc) in response.tool_calls.iter().enumerate() {
            let tool_name = tc.function.name.clone();
            let tool_args = tc.function.arguments.clone();
            let tc_id = tc.id.clone();
            let qualified_name = tool_name.clone(); // qualified_name is identity, no registry needed

            let mcp_call = McpToolCall {
                id: tc.id.clone(),
                name: tool_name.clone(),
                arguments: serde_json::from_str(&tc.function.arguments)
                    .unwrap_or(serde_json::json!({})),
            };

            let mut tool_ctx = cfg.ctx.clone();
            tool_ctx.current_thread_id = Some(thread.id);
            tool_ctx.current_channel_id = Some(thread.channel_id);
            tool_ctx.current_profile_name = Some(profile_name.to_string());
            tool_ctx.current_channel_name = Some(channel.name.clone());
            tool_ctx.current_platform = channel.platform.clone();
            tool_ctx.current_allowed_tools = prof.allowed_tools.clone();

            let pool = pool.clone();
            let pm = cfg.plugin_manager.clone();
            let seq = result_seqs[idx];
            let tid = thread.id;
            let iter_num = current_iter;

            // --- Phase 1: Read per-tool timeout from registry ---
            // Snapshot the registry outside the spawned task so we only read the lock once.
            let mcp_snapshot = pm.snapshot_registry().await;
            let timeout_secs = mcp_snapshot.get_timeout_secs(&tool_name);
            let timeout_dur = std::time::Duration::from_secs(timeout_secs);

            // Snapshot bg threshold BEFORE entering the spawned closure (cfg ref issue)
            let bg_threshold_secs = cfg.config_snapshot().tool_bg_secs;
            let bg_threshold = std::time::Duration::from_secs(bg_threshold_secs);
            let is_multi_tool = tool_count > 1;

            join_set.spawn(async move {

                // Execute with short timeout (fast path) + background fallback
                let tool_future = mcp_snapshot.execute(&mcp_call, tool_ctx.clone());

                let result = match tokio::time::timeout(bg_threshold, tool_future).await {
                    Ok(result) => result,
                    Err(_elapsed) => {
                        // Short timeout exceeded : switch to background mode.
                        // Register the tool in the task registry for polling.
                        let registry = crate::agent::task_registry::TASK_REGISTRY
                            .get()
                            .cloned()
                            .expect("TASK_REGISTRY not initialized");
                        let (task_id, abort_rx, _log_buffer) = registry
                            .register(tid, &tool_name)
                            .await;
                        let task_id_bg = task_id.clone();

                        // Spawn background task with the per-tool timeout
                        let bg_mcp_call = mcp_call.clone();
                        let bg_mcp_snapshot = mcp_snapshot.clone();
                        let bg_timeout = timeout_dur;
                        let bg_tool_name = tool_name.clone();
                        let bg_registry = registry.clone();

                        tokio::spawn(async move {
                            let bg_tool_future = bg_mcp_snapshot.execute(&bg_mcp_call, tool_ctx);
                            tokio::select! {
                                _ = abort_rx => {
                                    bg_registry.set_status(&task_id_bg,
                                        crate::agent::task_registry::TaskStatus::Cancelled).await;
                                    bg_registry.append_log(&task_id_bg,
                                        &format!("Tool '{}' was cancelled", bg_tool_name)).await;
                                    return;
                                }
                                result = tokio::time::timeout(bg_timeout, bg_tool_future) => {
                                    match result {
                                        Ok(Ok(res)) => {
                                            let truncated = truncate_content(
                                                &res.content, DEFAULT_MAX_TOOL_OUTPUT_CHARS);
                                            bg_registry.set_status(&task_id_bg,
                                                crate::agent::task_registry::TaskStatus::Completed(
                                                    truncated)).await;
                                        }
                                        Ok(Err(e)) => {
                                            let err = format!("Error: {}", e);
                                            bg_registry.set_status(&task_id_bg,
                                                crate::agent::task_registry::TaskStatus::Failed(
                                                    err)).await;
                                        }
                                        Err(_) => {
                                            let err = format!(
                                                "Tool '{}' exceeded long timeout ({}s)",
                                                bg_tool_name, bg_timeout.as_secs());
                                            bg_registry.set_status(&task_id_bg,
                                                crate::agent::task_registry::TaskStatus::Failed(
                                                    err)).await;
                                        }
                                    }
                                }
                            };
                        });

                        // Return a McpToolResult containing processing status
                        let processing_json = serde_json::json!({
                            "status": "processing",
                            "task_id": task_id,
                            "tool": qualified_name,
                            "timeout_secs": bg_threshold.as_secs(),
                            "message": format!(
                                "Tool '{}' started. Use poll_task, wait_task, or read_task_logs to check progress.",
                                tool_name
                            ),
                        });
                        Ok(McpToolResult {
                            call_id: tc_id.clone(),
                            content: processing_json.to_string(),
                            is_error: false,
                        })
                    }
                };

                let (output, is_error) = match &result {
                    Ok(res) => {
                        let truncated =
                            truncate_content(&res.content, DEFAULT_MAX_TOOL_OUTPUT_CHARS);
                        (truncated, false)
                    }
                    Err(e) => (format!("Error executing tool '{}': {}", tool_name, e), true),
                };

                // For multi-tool calls: JSON with tool/input/output for disambiguation.
                // For single tool calls: just the raw output (no wrapping).
                let content_str = if is_multi_tool {
                    let args_value: serde_json::Value =
                        serde_json::from_str(&tool_args).unwrap_or(serde_json::json!(tool_args));
                    serde_json::json!({
                        "tool": qualified_name,
                        "input": args_value,
                        "output": output,
                    }).to_string()
                } else {
                    output.clone()
                };

                // Persist single consolidated result message
                // (no separate "tool" call message anymore)
                let result_msg = MessageNew {
                    thread_id: tid,
                    role: "agent".to_string(),
                    content: content_str,
                    thread_sequence: seq,
                    external_id: None,
                    metadata: serde_json::json!({"is_error": is_error}),
                    embedding: None,
                    summary_text: None,
                    is_summary: false,
                    msg_type: "tool-result".to_string(),
                    msg_subtype: Some(qualified_name.clone()),
                    iteration_number: iter_num,
                    duration_ms: 0,
                    token_usage: serde_json::json!({}),
                };

                match helpers::persist_or_abort(&pool, &result_msg, tid).await {
                    helpers::CreateMessageResult::FkViolation => {
                        error!("FK violation: thread {} no longer exists", tid);
                    }
                    helpers::CreateMessageResult::OtherError(e) => {
                        error!("Failed to persist tool result '{}': {:?}", tool_name, e)
                    }
                    helpers::CreateMessageResult::Success(_) => {}
                }

                (idx, tc_id, tool_name, output, is_error)
            });
        }

        // Collect results as they complete (order may differ from call order)
        let mut tool_results: Vec<Option<(String, String, String)>> = vec![None; tool_count];
        while let Some(join_result) = join_set.join_next().await {
            match join_result {
                Ok((idx, tc_id, tool_name, output, _is_error)) => {
                    tool_results[idx] = Some((tc_id, tool_name, output));
                }
                Err(e) => {
                    error!("Tool execution task panicked: {:?}", e);
                }
            }
        }

        // Push LLM messages in original call order
        for (i, _tc) in response.tool_calls.iter().enumerate() {
            if let Some((tc_id, tool_name, output)) = &tool_results[i] {
                messages.push(ChatMessage::tool_result(tc_id, tool_name, output));
            }
        }

        // Proactive subtask reminder: if the LLM has made several tool call
        // rounds without managing subtasks, inject a gentle nudge.
        if enable_subtasks {
            // Check if any tool call in this round was manage_subtasks
            let called_manage = response
                .tool_calls
                .iter()
                .any(|tc| tc.function.name == "manage_subtasks");
            if called_manage {
                calls_since_subtask_management = 0;
            } else {
                calls_since_subtask_management += 1;
            }

            if calls_since_subtask_management >= 3 {
                if let Ok(subtasks) = crate::subtask::list_subtasks(&cfg.pool, thread.id).await {
                    let pending_count = subtasks
                        .iter()
                        .filter(|st| st.status == "pending" || st.status == "in_progress")
                        .count();
                    if pending_count > 0 {
                        let reminder = format!(
                            "[Progress Check] You've made {} tool call rounds without updating your subtasks. \
                             If you've completed any steps, call `manage_subtasks(action=\"update\", subtask_id=N, status=\"completed\")` \
                             for each finished subtask now. This keeps progress accurate.",
                            calls_since_subtask_management,
                        );
                        messages.push(ChatMessage::system(&reminder));
                        calls_since_subtask_management = 0;
                    }
                }
            }
        }
    } // end for _turn

    // If we exited the loop without a final text response, provide a fallback
    if final_content.is_empty() && !final_tool_call {
        final_content =
            "I've completed the requested operations using my available tools.".to_string();
    } else if final_content.is_empty() && final_tool_call {
        // The loop exhausted all iterations while the LLM was still issuing tool
        // calls: no final answer was produced. Set limit_reached (interrupted)
        // rather than force_failed so the thread is correctly marked as
        // interrupted (can be resumed) instead of failed (dead end).
        final_content = "The task ran out of iterations while still processing tools: no final answer was produced.".to_string();
        limit_reached = true;
    }

    // 7. Serialize cumulative token usage
    let token_usage_json = cumulative_usage.as_ref().map(|u| {
        serde_json::json!({
            "prompt_tokens": u.prompt_tokens,
            "completion_tokens": u.completion_tokens,
            "cached_tokens": u.cached_tokens,
            "reasoning_tokens": u.reasoning_tokens,
        })
    });

    // Build evidence metadata from context assembly
    let evidence_metadata = {
        let meta = serde_json::json!({
            "context": {
                "selected_message_ids": [],
                "wiki_files": [],
                "block_counts": {},
                "dropped_blocks": [],
                "total_chars": 0,
            },
            "grounding": {
                "policy_applied": true,
            }
        });
        /* ctx_assembly_meta removed: context comes from prompt tool */
        meta
    };

    // 8. If reasoning/thinking exists, save as its own record
    if let Some(ref reasoning_text) = final_reasoning {
        if !reasoning_text.is_empty() {
            let reasoning_msg = MessageNew {
                thread_id: thread.id,
                role: "agent".to_string(),
                content: reasoning_text.clone(),
                thread_sequence: {
                    let v = *next_seq;
                    *next_seq += 1;
                    v
                },
                external_id: None,
                metadata: serde_json::json!({
                    "context": evidence_metadata["context"],
                    "grounding": evidence_metadata["grounding"],
                }),
                embedding: None,
                summary_text: None,
                is_summary: false,
                msg_type: "reasoning".to_string(),
                msg_subtype: None,
                iteration_number: current_iter,
                duration_ms: 0,
                token_usage: serde_json::json!({}),
            };
            let reasoning_saved = queries::create_message(&cfg.pool, &reasoning_msg).await?;
            helpers::enqueue_delivery(
                &cfg.ctx,
                &reasoning_saved,
                &channel,
                thread,
                cause_msg.external_id.clone(),
            )
            .await;
        }
    }

    // 9. Save the main agent response (when limit_reached, generate LLM summary instead)
    // 9. Save the main agent response + cleanup
    let saved = handle_response(
        cfg, thread, cause_msg, &channel, *next_seq, start_time, &messages,
        &mut cumulative_usage, &mut force_failed, limit_reached, current_iter,
        iter_limit, &per_thread_llm, final_content, token_usage_json,
        evidence_metadata, enable_subtasks,
    ).await?;
    return Ok(saved)
}
